// astro/src/components/ConsentBanner.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useStore } from "@nanostores/vue";
import { Cookie } from "lucide-vue-next";
import { $consent, grant, deny, reset, initConsent, firePageView } from "@/stores/consent";

const consent = useStore($consent);

// Hydration-safe: SSR + first client render show the banner (consent === null,
// matching the store default). initConsent() restores the stored decision / GPC
// state after mount. The island is transition:persist, so this runs once and the
// astro:page-load listener persists across client navigations.
onMounted(() => {
  initConsent();
  document.addEventListener("astro:page-load", firePageView);
});
</script>

<template>
  <!-- aria-live so screen readers announce the banner when it appears post-hydration. -->
  <div aria-live="polite">
    <div
      v-if="consent === null"
      class="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-background/95 p-4 backdrop-blur"
    >
      <div class="mx-auto flex max-w-4xl flex-wrap items-center justify-between gap-3">
        <p class="text-sm text-dim">
          We use privacy-friendly analytics with your consent. Nothing is sent until you accept.
        </p>
        <div class="flex gap-2">
          <button type="button" class="btn-primary" @click="grant">Accept</button>
          <button type="button" class="btn-ghost" @click="deny">Decline</button>
        </div>
      </div>
    </div>

    <button
      v-else
      type="button"
      class="focus-ring fixed bottom-4 right-4 z-40 rounded-full border border-border bg-background p-3 text-dim hover:text-foreground"
      aria-label="Cookie preferences"
      @click="reset"
    >
      <Cookie :size="18" aria-hidden="true" />
    </button>
  </div>
</template>

// src/components/ConsentBanner.tsx
import { useState, useEffect, type JSX } from "react";
import { Link } from "react-router";
import { Cookie } from "lucide-react";
import { useConsent } from "@/hooks/useConsent";

export function ConsentBanner(): JSX.Element | null {
  const { consent, grant, deny, reset } = useConsent();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true); // eslint-disable-line react-hooks/set-state-in-effect -- mount guard; SSG requires a safe default (null) on first render so the banner is absent from prerendered HTML and cannot become the LCP element
  }, []);

  if (!mounted) return null;

  if (consent !== null) {
    return (
      <button
        type="button"
        onClick={reset}
        aria-label="Change cookie preferences"
        title="Change cookie preferences"
        style={{ bottom: 'calc(env(safe-area-inset-bottom, 0px) + 5rem)' }}
        className="fixed right-4 z-50 flex h-11 w-11 items-center justify-center rounded-full border border-border bg-background text-muted-foreground shadow-md transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
      >
        <Cookie size={18} aria-hidden="true" />
      </button>
    );
  }

  return (
    <div
      role="region"
      aria-label="Cookie consent"
      aria-live="polite"
      style={{ paddingBottom: 'env(safe-area-inset-bottom, 0px)' }}
      className="fixed bottom-0 left-0 right-0 z-50 border-t border-border bg-background shadow-lg"
    >
      <div className="mx-auto flex max-w-screen-xl flex-col gap-4 px-4 py-5 sm:flex-row sm:items-start sm:gap-8 sm:px-6">
        <div className="flex-1 space-y-1">
          <p className="text-sm text-foreground">This site uses analytics cookies</p>
          <p className="text-sm text-muted-foreground">
            We use Google Analytics to understand how visitors use offon.dev. No data is sent to
            Google until you accept. You can change your preference at any time. See our{" "}
            <Link
              to="/privacy"
              className="underline underline-offset-2 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 rounded-sm"
            >
              Privacy Policy
            </Link>{" "}
            for details.
          </p>
        </div>
        <div className="flex shrink-0 flex-wrap gap-2 sm:items-center">
          <button
            type="button"
            onClick={deny}
            aria-label="Decline analytics cookies"
            className="btn-ghost"
          >
            Decline
          </button>
          <button
            type="button"
            onClick={grant}
            aria-label="Accept analytics cookies"
            className="btn-primary"
          >
            Accept Analytics
          </button>
        </div>
      </div>
    </div>
  );
}
